[package]
name = "mfn-layer2-dsr"
version = "0.1.0"
edition = "2021"
authors = ["HyperMesh Team"]
description = "MFN Layer 2: Dynamic Similarity Reservoir with Spiking Neural Networks"
license = "MIT OR Apache-2.0"


[lib]
path = "lib.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.38", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Machine learning and neural networks
candle-core = "0.4"
candle-nn = "0.4"
ndarray = "0.15"
nalgebra = "0.32"

# Spiking neural network implementation
rand = "0.8"
rand_distr = "0.4"

# Data structures and concurrency
dashmap = "6.0"
arc-swap = "1.7"
crossbeam = "0.8"
parking_lot = "0.12"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Hashing and utilities
sha2 = "0.10"
blake3 = "1.5"
uuid = "1.0"
thiserror = "1.0"
anyhow = "1.0"

# Time and metrics
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"

# Integration with STOQ protocol
stoq = { path = "../../../protocols/stoq" }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio", "html_reports"] }
proptest = "1.4"
tempfile = "3.10"
tokio-test = "0.4"

[features]
default = ["stoq-integration", "metrics"]
stoq-integration = []
metrics = []
benchmarks = []

[[bench]]
name = "dsr_performance"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
inherits = "release"
debug = true