// Copyright 2026 Hypermesh Foundation. All rights reserved.
// Licensed under the Business Source License 1.1.
// See the LICENSE file in the repository root for full license text.

//! Ephemeral Certificate Generation for Anonymous Mode
//!
//! Generates self-signed certificates for QUIC TLS handshakes without
//! involving the CA or Certificate Transparency. These certificates are
//! meant to be used once and discarded -- no persistence, no CT logging,
//! no consensus proofs.

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{Duration, SystemTime};

use rcgen::{CertificateParams, Ia5String, KeyPair, SanType};

use crate::errors::{TrustChainError, Result};

/// Configuration for ephemeral certificate generation.
pub struct EphemeralCertConfig {
    /// Certificate validity duration in seconds. Default: 86400 (24 hours).
    pub validity_secs: u64,
    /// Key algorithm name (informational). Default: "FALCON-1024".
    pub key_algorithm: String,
    /// Prefix for generated common names. Default: "ephemeral".
    pub common_name_prefix: String,
}

impl Default for EphemeralCertConfig {
    fn default() -> Self {
        Self {
            validity_secs: 86400,
            key_algorithm: "FALCON-1024".to_string(),
            common_name_prefix: "ephemeral".to_string(),
        }
    }
}

/// A self-signed ephemeral certificate with associated metadata.
pub struct EphemeralCertificate {
    /// DER-encoded X.509 certificate.
    pub cert_der: Vec<u8>,
    /// DER-encoded private key.
    pub private_key_der: Vec<u8>,
    /// BLAKE3 fingerprint of the DER certificate.
    pub fingerprint: [u8; 32],
    /// When the certificate was created.
    pub created_at: SystemTime,
    /// When the certificate expires.
    pub expires_at: SystemTime,
    /// Optional tunnel identifier (set for tunnel-specific certs).
    pub tunnel_id: Option<String>,
    /// Optional hop number within a tunnel.
    pub hop_number: Option<u32>,
}

/// Generates ephemeral self-signed certificates for anonymous QUIC handshakes.
///
/// No CA involvement, no CT logging, no consensus proofs, no persistence.
pub struct EphemeralCertificateGenerator {
    config: EphemeralCertConfig,
    certs_generated: AtomicU64,
}

impl EphemeralCertificateGenerator {
    /// Create a new generator with the given configuration.
    pub fn new(config: EphemeralCertConfig) -> Self {
        Self {
            config,
            certs_generated: AtomicU64::new(0),
        }
    }

    /// Generate an ephemeral self-signed certificate.
    pub fn generate(&self) -> Result<EphemeralCertificate> {
        let cn = format!("{}-{}", self.config.common_name_prefix, uuid::Uuid::new_v4());
        self.generate_inner(&cn, None, None)
    }

    /// Generate an ephemeral certificate bound to a specific tunnel hop.
    ///
    /// The tunnel ID and hop number are embedded as subject alternative names
    /// so the peer can verify tunnel membership without a CA.
    pub fn generate_for_tunnel(
        &self,
        tunnel_id: &str,
        hop_number: u32,
    ) -> Result<EphemeralCertificate> {
        let cn = format!(
            "{}-{}-hop{}",
            self.config.common_name_prefix, tunnel_id, hop_number
        );
        self.generate_inner(&cn, Some(tunnel_id.to_string()), Some(hop_number))
    }

    /// Number of certificates generated by this instance.
    pub fn certs_generated(&self) -> u64 {
        self.certs_generated.load(Ordering::Relaxed)
    }

    // -- internal -----------------------------------------------------------

    fn generate_inner(
        &self,
        common_name: &str,
        tunnel_id: Option<String>,
        hop_number: Option<u32>,
    ) -> Result<EphemeralCertificate> {
        let now = SystemTime::now();
        let validity = Duration::from_secs(self.config.validity_secs);
        let expires_at = now + validity;

        let mut params = CertificateParams::new(vec![common_name.to_string()]).map_err(|e| {
            TrustChainError::CertificateGenerationFailed {
                reason: format!("certificate params: {e}"),
            }
        })?;

        // If tunnel metadata is present, add a SAN so it is visible in the cert.
        if let (Some(tid), Some(hop)) = (&tunnel_id, hop_number) {
            let tunnel_san = format!("{}-hop{}.tunnel.local", tid, hop);
            let tunnel_ia5 = Ia5String::try_from(tunnel_san.as_str()).map_err(|e| {
                TrustChainError::CertificateGenerationFailed {
                    reason: format!("invalid tunnel SAN: {e}"),
                }
            })?;
            params
                .subject_alt_names
                .push(SanType::DnsName(tunnel_ia5));
        }

        params.not_before = now.into();
        params.not_after = expires_at.into();

        // Generate a fresh key pair and self-sign.
        let key_pair = KeyPair::generate().map_err(|e| {
            TrustChainError::CertificateGenerationFailed {
                reason: format!("key generation: {e}"),
            }
        })?;

        let cert = params.self_signed(&key_pair).map_err(|e| {
            TrustChainError::CertificateGenerationFailed {
                reason: format!("self-signing: {e}"),
            }
        })?;

        let cert_der = cert.der().to_vec();
        let private_key_der = key_pair.serialize_der();
        let fingerprint: [u8; 32] = blake3::hash(&cert_der).into();

        self.certs_generated.fetch_add(1, Ordering::Relaxed);

        Ok(EphemeralCertificate {
            cert_der,
            private_key_der,
            fingerprint,
            created_at: now,
            expires_at,
            tunnel_id,
            hop_number,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let cfg = EphemeralCertConfig::default();
        assert_eq!(cfg.validity_secs, 86400);
        assert_eq!(cfg.key_algorithm, "FALCON-1024");
        assert_eq!(cfg.common_name_prefix, "ephemeral");
    }

    #[test]
    fn test_generate_ephemeral_cert() {
        let gen = EphemeralCertificateGenerator::new(EphemeralCertConfig::default());
        let cert = gen.generate().expect("test: generate ephemeral cert");

        assert!(!cert.cert_der.is_empty(), "cert DER should be non-empty");
        assert!(!cert.private_key_der.is_empty(), "private key should be non-empty");
        assert_ne!(cert.fingerprint, [0u8; 32], "fingerprint should be non-zero");
        assert!(cert.tunnel_id.is_none());
        assert!(cert.hop_number.is_none());

        // Validity window should match config (24h).
        let duration = cert
            .expires_at
            .duration_since(cert.created_at)
            .expect("test: expires_at > created_at");
        assert_eq!(duration.as_secs(), 86400);
    }

    #[test]
    fn test_generate_tunnel_cert() {
        let gen = EphemeralCertificateGenerator::new(EphemeralCertConfig::default());
        let cert = gen
            .generate_for_tunnel("tun-abc-123", 2)
            .expect("test: generate tunnel cert");

        assert_eq!(cert.tunnel_id.as_deref(), Some("tun-abc-123"));
        assert_eq!(cert.hop_number, Some(2));
        assert!(!cert.cert_der.is_empty());
    }

    #[test]
    fn test_certs_have_unique_fingerprints() {
        let gen = EphemeralCertificateGenerator::new(EphemeralCertConfig::default());
        let a = gen.generate().expect("test: cert a");
        let b = gen.generate().expect("test: cert b");

        assert_ne!(a.fingerprint, b.fingerprint, "two certs must have different fingerprints");
    }

    #[test]
    fn test_custom_validity() {
        let cfg = EphemeralCertConfig {
            validity_secs: 3600,
            ..Default::default()
        };
        let gen = EphemeralCertificateGenerator::new(cfg);
        let cert = gen.generate().expect("test: custom validity cert");

        let duration = cert
            .expires_at
            .duration_since(cert.created_at)
            .expect("test: expires_at > created_at");
        assert_eq!(duration.as_secs(), 3600);
    }

    #[test]
    fn test_counter_increments() {
        let gen = EphemeralCertificateGenerator::new(EphemeralCertConfig::default());
        assert_eq!(gen.certs_generated(), 0);

        let _a = gen.generate().expect("test: cert 1");
        let _b = gen.generate().expect("test: cert 2");
        let _c = gen.generate().expect("test: cert 3");

        assert_eq!(gen.certs_generated(), 3);
    }
}
