// Copyright 2026 Hypermesh Foundation. All rights reserved.
// Licensed under the Business Source License 1.1.
// See the LICENSE file in the repository root for full license text.

//! Execution Scheduler - Consensus-aware task scheduling with asset optimization
//!
//! This scheduler coordinates execution tasks with asset allocation and consensus
//! validation requirements. It optimizes resource allocation across multiple
//! executions while maintaining consensus proof validation.

mod analysis;
mod dispatch;

use std::sync::Arc;
use std::collections::{HashMap, BinaryHeap};
use std::time::{SystemTime, Duration};
use std::cmp::Ordering;
use anyhow::Result;
use serde::{Serialize, Deserialize};
use tokio::sync::{RwLock, Mutex, Semaphore};
// uuid::Uuid used in dispatch.rs via full path

use crate::catalog::vm::consensus::{ConsensusVM, ConsensusOperation};
use crate::assets::core::AssetType;
use super::context::ExecutionContext;
use super::super::AssetManagementConfig;

/// Execution scheduler with consensus-aware resource allocation
pub struct ExecutionScheduler {
    /// Consensus VM for validation
    _consensus_vm: Arc<RwLock<ConsensusVM>>,
    /// Asset management configuration
    _asset_config: AssetManagementConfig,
    /// Pending execution queue
    pending_queue: Arc<RwLock<BinaryHeap<ScheduledExecution>>>,
    /// Running executions tracker
    running_executions: Arc<RwLock<HashMap<String, RunningExecution>>>,
    /// Resource availability tracker
    resource_tracker: Arc<RwLock<ResourceTracker>>,
    /// Scheduler metrics
    metrics: Arc<Mutex<SchedulerMetrics>>,
    /// Concurrency limits
    _execution_semaphore: Arc<Semaphore>,
    /// Configuration
    config: SchedulerConfig,
}

/// Execution plan generated by scheduler
#[derive(Debug, Clone)]
pub struct ExecutionPlan {
    /// Unique execution identifier
    pub execution_id: String,
    /// Code to execute
    pub code: String,
    /// Programming language
    pub language: String,
    /// Required asset allocations
    pub required_assets: HashMap<AssetType, u64>,
    /// Consensus operation for validation
    pub consensus_operation: ConsensusOperation,
    /// Execution priority
    pub priority: ExecutionPriority,
    /// Estimated execution time
    pub estimated_duration: Duration,
    /// Resource optimization strategy
    pub optimization_strategy: OptimizationStrategy,
    /// Execution constraints
    pub constraints: ExecutionConstraints,
}

/// Scheduled execution with priority queue ordering
#[derive(Debug, Clone)]
pub struct ScheduledExecution {
    /// Execution plan
    pub plan: ExecutionPlan,
    /// Execution context
    pub context: Arc<ExecutionContext>,
    /// Scheduled timestamp
    pub scheduled_at: SystemTime,
    /// Execution deadline (optional)
    pub deadline: Option<SystemTime>,
    /// Scheduling priority score
    pub priority_score: f64,
}

impl PartialEq for ScheduledExecution {
    fn eq(&self, other: &Self) -> bool {
        self.priority_score.partial_cmp(&other.priority_score) == Some(Ordering::Equal)
    }
}

impl Eq for ScheduledExecution {}

impl PartialOrd for ScheduledExecution {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        other.priority_score.partial_cmp(&self.priority_score)
    }
}

impl Ord for ScheduledExecution {
    fn cmp(&self, other: &Self) -> Ordering {
        self.partial_cmp(other).unwrap_or(Ordering::Equal)
    }
}

/// Running execution tracker
#[derive(Debug, Clone)]
pub struct RunningExecution {
    pub execution_id: String,
    pub started_at: SystemTime,
    pub estimated_completion: SystemTime,
    pub allocated_resources: HashMap<AssetType, u64>,
    pub context: Arc<ExecutionContext>,
}

/// Resource availability tracker
#[derive(Debug, Default)]
pub struct ResourceTracker {
    pub available_cpu_cores: u32,
    pub available_memory: u64,
    pub available_gpu_cores: u32,
    pub available_storage: u64,
    pub available_bandwidth: u64,
    pub reservations: HashMap<String, ResourceReservation>,
}

/// Resource reservation for scheduled executions
#[derive(Debug, Clone)]
pub struct ResourceReservation {
    pub execution_id: String,
    pub reserved_resources: HashMap<AssetType, u64>,
    pub reservation_expires: SystemTime,
}

/// Execution priority levels
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum ExecutionPriority {
    Low = 1,
    Normal = 2,
    High = 3,
    Critical = 4,
    Emergency = 5,
}

impl Default for ExecutionPriority {
    fn default() -> Self {
        ExecutionPriority::Normal
    }
}

/// Resource optimization strategies
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OptimizationStrategy {
    Speed,
    Efficiency,
    Balanced,
    Throughput,
    Custom(OptimizationParameters),
}

/// Custom optimization parameters
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimizationParameters {
    pub cpu_weight: f64,
    pub memory_weight: f64,
    pub gpu_weight: f64,
    pub network_weight: f64,
    pub latency_weight: f64,
    pub throughput_weight: f64,
}

/// Execution constraints
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionConstraints {
    pub max_execution_time: Option<Duration>,
    pub max_memory_usage: Option<u64>,
    pub max_cpu_cores: Option<u32>,
    pub min_consensus_level: ConsensusValidationLevel,
    pub asset_isolation: AssetIsolationLevel,
}

/// Consensus validation levels
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ConsensusValidationLevel {
    Basic,
    Standard,
    Enhanced,
    Complete,
}

/// Asset isolation levels
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AssetIsolationLevel {
    None,
    Process,
    Container,
    VM,
    Hardware,
}

/// Scheduler configuration
#[derive(Debug, Clone)]
pub struct SchedulerConfig {
    pub max_concurrent_executions: u32,
    pub scheduling_quantum: Duration,
    pub oversubscription_ratio: f64,
    pub priority_aging_factor: f64,
    pub deadline_urgency_factor: f64,
    pub enable_preemption: bool,
}

impl Default for SchedulerConfig {
    fn default() -> Self {
        Self {
            max_concurrent_executions: 10,
            scheduling_quantum: Duration::from_millis(100),
            oversubscription_ratio: 1.2,
            priority_aging_factor: 0.1,
            deadline_urgency_factor: 2.0,
            enable_preemption: false,
        }
    }
}

/// Scheduler performance metrics
#[derive(Debug, Default)]
pub struct SchedulerMetrics {
    pub total_scheduled: u64,
    pub total_completed: u64,
    pub total_failed: u64,
    pub average_wait_time: Duration,
    pub average_execution_time: Duration,
    pub resource_utilization: HashMap<AssetType, f64>,
    pub queue_length: usize,
    pub preemptions: u64,
}

impl ExecutionScheduler {
    /// Create new execution scheduler
    pub async fn new(
        consensus_vm: Arc<RwLock<ConsensusVM>>,
        asset_config: AssetManagementConfig,
    ) -> Result<Self> {
        let config = SchedulerConfig::default();
        let execution_semaphore = Arc::new(Semaphore::new(config.max_concurrent_executions as usize));

        Ok(Self {
            _consensus_vm: consensus_vm,
            _asset_config: asset_config,
            pending_queue: Arc::new(RwLock::new(BinaryHeap::new())),
            running_executions: Arc::new(RwLock::new(HashMap::new())),
            resource_tracker: Arc::new(RwLock::new(ResourceTracker::default())),
            metrics: Arc::new(Mutex::new(SchedulerMetrics::default())),
            _execution_semaphore: execution_semaphore,
            config,
        })
    }

    /// Get scheduler metrics
    pub async fn get_metrics(&self) -> SchedulerMetrics {
        let metrics = self.metrics.lock().await;
        metrics.clone()
    }
}

/// Code complexity levels
#[derive(Debug, Clone)]
pub(crate) enum CodeComplexity {
    Low,
    Medium,
    High,
    VeryHigh,
}

/// Queue status information
#[derive(Debug, Clone)]
pub struct QueueStatus {
    pub pending_count: usize,
    pub running_count: usize,
    pub total_capacity: u32,
    pub next_execution_eta: Option<SystemTime>,
}

impl Clone for SchedulerMetrics {
    fn clone(&self) -> Self {
        Self {
            total_scheduled: self.total_scheduled,
            total_completed: self.total_completed,
            total_failed: self.total_failed,
            average_wait_time: self.average_wait_time,
            average_execution_time: self.average_execution_time,
            resource_utilization: self.resource_utilization.clone(),
            queue_length: self.queue_length,
            preemptions: self.preemptions,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::catalog::vm::consensus::ConsensusVM;
    use crate::catalog::vm::ConsensusRequirements;

    #[tokio::test]
    async fn test_scheduler_creation() {
        let requirements = ConsensusRequirements::default();
        let consensus_vm = Arc::new(RwLock::new(ConsensusVM::new(requirements).expect("test: create consensus vm")));
        let asset_config = AssetManagementConfig::default();

        let scheduler = ExecutionScheduler::new(consensus_vm, asset_config).await;
        assert!(scheduler.is_ok());
    }

    #[tokio::test]
    async fn test_resource_requirements_analysis() {
        let requirements = ConsensusRequirements::default();
        let consensus_vm = Arc::new(RwLock::new(ConsensusVM::new(requirements).expect("test: create consensus vm")));
        let asset_config = AssetManagementConfig::default();
        let scheduler = ExecutionScheduler::new(consensus_vm, asset_config).await.expect("test: create scheduler");

        let julia_code = "using Nova\nfor i in 1:1000\n    println(i)\nend";
        let requirements = scheduler.analyze_resource_requirements(julia_code, "julia").await.expect("test: analyze");

        assert!(requirements.contains_key(&AssetType::Cpu));
        assert!(requirements.contains_key(&AssetType::Memory));
        assert!(requirements.contains_key(&AssetType::Gpu));
    }

    #[tokio::test]
    async fn test_code_complexity_analysis() {
        let requirements = ConsensusRequirements::default();
        let consensus_vm = Arc::new(RwLock::new(ConsensusVM::new(requirements).expect("test: create consensus vm")));
        let asset_config = AssetManagementConfig::default();
        let scheduler = ExecutionScheduler::new(consensus_vm, asset_config).await.expect("test: create scheduler");

        let simple_code = "println(\"Hello, World!\")";
        let complexity = scheduler.analyze_code_complexity(simple_code, "julia").await.expect("test: analyze");
        assert!(matches!(complexity, CodeComplexity::Low));

        let complex_code = "for i in 1:1000\n    for j in 1:1000\n        if i > j\n            function complex_calc(x)\n                sort([x, x+1, x-1])\n            end\n        end\n    end\nend";
        let complexity = scheduler.analyze_code_complexity(complex_code, "julia").await.expect("test: analyze");
        assert!(matches!(complexity, CodeComplexity::High | CodeComplexity::VeryHigh));
    }

    #[tokio::test]
    async fn test_execution_priority_ordering() {
        let exec1 = ScheduledExecution {
            plan: ExecutionPlan {
                execution_id: "1".to_string(),
                code: "test".to_string(),
                language: "julia".to_string(),
                required_assets: HashMap::new(),
                consensus_operation: ConsensusOperation::default(),
                priority: ExecutionPriority::Low,
                estimated_duration: Duration::from_secs(10),
                optimization_strategy: OptimizationStrategy::Balanced,
                constraints: ExecutionConstraints {
                    max_execution_time: None,
                    max_memory_usage: None,
                    max_cpu_cores: None,
                    min_consensus_level: ConsensusValidationLevel::Complete,
                    asset_isolation: AssetIsolationLevel::Process,
                },
            },
            context: Arc::new(ExecutionContext::default()),
            scheduled_at: SystemTime::now(),
            deadline: None,
            priority_score: 100.0,
        };

        let exec2 = ScheduledExecution {
            plan: ExecutionPlan {
                execution_id: "2".to_string(),
                code: "test".to_string(),
                language: "julia".to_string(),
                required_assets: HashMap::new(),
                consensus_operation: ConsensusOperation::default(),
                priority: ExecutionPriority::High,
                estimated_duration: Duration::from_secs(10),
                optimization_strategy: OptimizationStrategy::Balanced,
                constraints: ExecutionConstraints {
                    max_execution_time: None,
                    max_memory_usage: None,
                    max_cpu_cores: None,
                    min_consensus_level: ConsensusValidationLevel::Complete,
                    asset_isolation: AssetIsolationLevel::Process,
                },
            },
            context: Arc::new(ExecutionContext::default()),
            scheduled_at: SystemTime::now(),
            deadline: None,
            priority_score: 300.0,
        };

        assert!(exec2 > exec1);
    }
}
