// AUTO-GENERATED by scripts/sync-status.ts
// DO NOT EDIT - update crate-status.toml files instead

export interface CrateStatus {
  id: string;
  name: string;
  description: string;
  phase: "planning" | "alpha" | "beta" | "stable";
  features: {
    working: string[];
    inDevelopment: string[];
    planned: string[];
  };
  completion: number;
}

export const crateStatuses: CrateStatus[] = [
  {
    "id": "block-matrix",
    "name": "Block-MATRIX",
    "description": "3D mesh topology, matrix-aware distributed computing, and asset pipeline",
    "phase": "alpha",
    "features": {
      "working": [
        "3D coordinate system (x,y,z positioning)",
        "Tensor math library (Vector3D, Matrix3x3, A*)",
        "Every-node blockchain (independent chains)",
        "Geospatial module (GPS conversion, clustering)",
        "Asset adapters (CPU/GPU/Memory/Storage/Network/Container)",
        "Privacy allocation (PrivacyMode: Anonymous/Private/Public)",
        "Matrix persistence (WAL, snapshots, recovery)",
        "Proof of State four-proof validation",
        "eBPF security manager with XDP attachment and policy enforcement",
        "ExtensionValidator for HyperMesh headers (PoS, asset hash, routing, privacy)",
        "Security integration framework (eBPF manager, syscall tracing, metrics collection)",
        "Privacy-eBPF bridge (PrivacyEbpfBridge tier updates, flexibility matrix, sync_to_kernel)",
        "Asset pipeline (Compress→Encrypt(Kyber-1024)→Shard→Distribute, correct order)",
        "Instruction-based retrieval (shard maps, client assembly, fallback strategies, <1KB instructions)"
      ],
      "inDevelopment": [
        "Network scope sync + reflector pooling — Device↔Network chain synchronization (wired: SyncManager, ReflectorPool, BlockTransport, SyncDispatcher)",
        "Gateway architecture for cross-scope asset transfers and scope bridging (GatewayManager, ScopeBridge, AssetTransfer lifecycle)",
        "Dynamic shard rebalancing (RebalanceManager with join/leave/failure triggers, octant diversity, cooldown)"
      ],
      "planned": [
        "Tensor operations for cross-network transaction routing (NGauge↔Caesar matrix coordination)",
        "Cross-scope proxy routing — NAT-like asset access across blockchain scope boundaries",
        "Container runtime with isolation",
        "Multi-node production deployment",
        "Cross-platform node binary (Linux/macOS/Windows) with 1-click installation",
        "CLI for matrix topology queries, node management, and asset operations"
      ]
    },
    "completion": 61
  },
  {
    "id": "caesar",
    "name": "Caesar",
    "description": "Gold-pegged interop bridge for multi-chain and fiat payment integration",
    "phase": "planning",
    "features": {
      "working": [
        "Token economics configuration",
        "Wallet creation and balance tracking",
        "Transaction processing engine",
        "Reward calculation framework",
        "Staking manager with APY",
        "Exchange rate engine",
        "Cross-chain bridge types (8 networks)"
      ],
      "inDevelopment": [
        "Banking provider STOQ migration",
        "Analytics engine integration",
        "STOQ API server endpoints"
      ],
      "planned": [
        "Live multi-chain bridge (BTC/ETH/SOL)",
        "Fiat payment processing",
        "Reward distribution system",
        "Gold peg stabilization mechanism",
        "Actual stake storage implementation",
        "Balance lookup service (actual implementation)",
        "Full transaction processing pipeline — end-to-end CAES settlement with asset integration",
        "NGauge tensor-coordinated transaction routing across the Caesar network",
        "caesar.hypermesh.online clearnet gateway for external integration",
        "Caesar SDK for third-party payment integration",
        "Caesar CLI for wallet management and transaction operations"
      ]
    },
    "completion": 33
  },
  {
    "id": "catalog",
    "name": "Catalog",
    "description": "Asset package registry and template library",
    "phase": "alpha",
    "features": {
      "working": [
        "Asset package types and metadata",
        "Asset registry with publish/install/search",
        "Template generation framework",
        "Asset validation pipeline",
        "Semantic versioning and dependency resolution",
        "HyperMesh execution delegation",
        "Scripting engine (syntax validation)",
        "Canonical asset type integration with lib↔blockmatrix compat layer"
      ],
      "inDevelopment": [
        "STOQ transport for distribution",
        "Content-addressed storage (DHT)",
        "TrustChain security integration"
      ],
      "planned": [
        "Full asset marketplace",
        "Peer-to-peer package sharing",
        "Consensus proof validation for packages",
        "Asset SDK for third-party developers (publish, discover, integrate)",
        "Asset transaction integration with Caesar settlement pipeline",
        "catalog.hypermesh.online clearnet registry access"
      ]
    },
    "completion": 47
  },
  {
    "id": "gateway",
    "name": "Gateway",
    "description": "HTTP/3 gateway for *.hypermesh.online domains and federated entry points",
    "phase": "planning",
    "features": {
      "working": [
        "QUIC/HTTP3 server setup (quinn + h3)",
        "TLS certificate loading (PEM/DER)",
        "Connection pool with health checks",
        "Router with path-based backend selection",
        "Circuit breaker and retry logic",
        "CORS middleware and request logging"
      ],
      "inDevelopment": [
        "Request handling (h3 API fix needed)",
        "HTTP/3 backend proxying"
      ],
      "planned": [
        "Federated gateway mesh",
        "STOQ protocol bridge",
        "Load balancing across backends",
        "Rate limiting and DDoS protection",
        "Multi-domain routing (trust/caesar/nguage/catalog.hypermesh.online)",
        "REST and GraphQL API layer for clearnet integration",
        "API documentation (OpenAPI/GraphQL schema)"
      ]
    },
    "completion": 40
  },
  {
    "id": "hypermesh-ebpf",
    "name": "HyperMesh eBPF",
    "description": "Unified eBPF intelligence layer - single source of truth for all packet processing",
    "phase": "alpha",
    "features": {
      "working": [
        "HyperMeshEbpf orchestrator API — capability detection, state management, graceful degradation (Full eBPF+AF_XDP → eBPF only → userspace)",
        "AF_XDP zero-copy I/O — 4-ring UMEM buffers, frame allocator, batch send/receive via syscalls",
        "C kernel XDP programs — counter, kprobe, tracepoint, HyperMesh XDP with extension header parsing (magic 0x484D)",
        "AF_XDP kernel integration — xsk_map redirect, UMEM mmap lifecycle, socket reuse across send/receive paths",
        "BPF map policy enforcement — policy/PoS/asset/xsk maps with 32-byte LE serialization and sync_to_kernel",
        "PacketDecision three-path routing — Pass (local), Redirect (AF_XDP→STOQ), Forward (XDP_TX to matrix node), Drop",
        "PoS pre-validation pipeline — header parsing, algorithm indicators, difficulty checks, FastValidationResult",
        "Validation hooks — STOQ (certificate, packet) + BlockMatrix (extension) registered via set_validation_hooks()",
        "Asset hash verification (BLAKE3) and blockchain registry validation",
        "Matrix routing path validation (IPv6 + matrix position encoding)",
        "Privacy tier eBPF enforcement with per-policy flag control",
        "Orchestrator state storage — routing rules, asset hashes, PoS validation state persisted across sessions",
        "build.rs auto-compilation of C eBPF programs (ebpf-loader feature gate)",
        "Unified intelligence + transport metrics collection"
      ],
      "inDevelopment": [],
      "planned": [
        "Kernel-space PoS validation at line rate",
        "Hardware offload support (smart NICs)",
        "Multi-queue AF_XDP load balancing"
      ]
    },
    "completion": 82
  },
  {
    "id": "hypermesh-lib",
    "name": "HyperMesh Lib",
    "description": "Shared canonical types for the HyperMesh ecosystem",
    "phase": "alpha",
    "features": {
      "working": [
        "NodeId, AssetId, NetworkId, and ContentHash newtypes",
        "PrivacyMode struct (2-axis: AccessScope + tracked)",
        "BlockchainScope enum (Device | Network)",
        "ProofType enum (PoSpace/PoStake/PoWork/PoTime)",
        "MatrixPosition coordinate type with distance_to and ORIGIN",
        "PipelineStage enum",
        "CryptoAlgorithm enum (Falcon/Kyber/AES)",
        "HypermeshError unified error type",
        "Three-pillar asset system (AssetKind + BaseState/AssetStatusTrait + AssetAdapter)",
        "Canonical Proof of State types (SpaceProof/StakeProof/WorkProof/TimeProof/ProofOfState)",
        "Cross-crate validation helpers (NodeId/AssetId/ContentHash/MatrixPosition)",
        "sanitize_identifier utility function",
        "Validatable trait and ProofValidationResult",
        "WorkCategory enum (Compute/Network/Storage/Cryptographic/Validation)"
      ],
      "inDevelopment": [
        "BlockMatrix/TrustChain migration to canonical asset types"
      ],
      "planned": [
        "Runtime state unification — all HyperMesh network execution and on-chain operations use Asset typedefs/impls",
        "Shared serialization formats",
        "Common test utilities",
        "Public SDK types for third-party integration (stable API surface)"
      ]
    },
    "completion": 74
  },
  {
    "id": "stoq",
    "name": "STOQ Protocol",
    "description": "QUIC-based transport protocol with eBPF acceleration and FALCON-1024 signing",
    "phase": "alpha",
    "features": {
      "working": [
        "QUIC/IPv6 transport — connection pooling, health checks, adaptive congestion control",
        "FALCON-1024 crypto — key generation, signing, dynamic key_id, real signature verification via FalconTrustChainClient",
        "Certificate management (4 strategies: self-signed, CA-issued, ACME, manual)",
        "Network isolation — PrivacyMode (Anonymous/Private/Public) with eBPF policy push and tunnel traffic type enforcement",
        "eBPF-accelerated send/receive — AF_XDP zero-copy I/O via StoqEbpfTransport thin consumer wrapper",
        "eBPF validation hooks — CertificateValidator + PacketValidator registered with hypermesh-ebpf orchestrator",
        "Kernel eBPF program loading via hypermesh-ebpf ebpf-loader feature gate",
        "Protocol extensions — packets, tokens, shards with canonical length-prefixed serialization",
        "PoS/PoW validation — hash-meets-difficulty checks, results fed to eBPF policy layer",
        "Transport metrics collection",
        "Matrix-aware positioning via hypermesh_lib canonical types"
      ],
      "inDevelopment": [],
      "planned": [
        "Protocol-level PoS token validation at line rate",
        "Adaptive transport tiers",
        "Multi-path QUIC",
        "Reflector pool transport — redundancy/sync protocol for Public and Federated blockchain scopes"
      ]
    },
    "completion": 73
  },
  {
    "id": "trustchain",
    "name": "TrustChain",
    "description": "FALCON-1024 Certificate Authority with Proof of State validation",
    "phase": "alpha",
    "features": {
      "working": [
        "Certificate Authority — issuance, revocation, X.509 chain validation with rcgen + x509-parser",
        "FALCON-1024 post-quantum signing — real keypair generation, signing, verification via pqcrypto_falcon",
        "Kyber-1024 key encapsulation — KEM keypair, encapsulate, decapsulate via pqcrypto_kyber",
        "Proof of State four-proof validation — PoSpace (filesystem), PoStake (network), PoWork (computational), PoTime (NTP sync)",
        "Security monitoring — Byzantine detection (replay, time manipulation, storage falsification), severity-scored alerts, dashboards",
        "DNS-over-QUIC resolver with STOQ transport, caching, TTL management, DNSSEC option",
        "STOQ-based API server with request/response types for certificate and DNS operations",
        "Deployment quality gates — 6 validators (security theater, consensus, HSM removal, mock response, production readiness, DNS)",
        "CLI tools (trustchain_bootstrap, trustchain_ca, stoq-server, http3-server, validate-deployment)",
        "Certificate Transparency — RFC 6962 compliant Merkle tree (MTH, inclusion proofs, consistency proofs), SCTs, SignedTreeHead",
        "Production certificate hardening — SecurityIntegratedCA with mandatory consensus, FALCON-1024 validation, real metrics",
        "Trust scoring / reputation system — weighted violations, time decay (24h half-life), TrustLevel classification, audit trail"
      ],
      "inDevelopment": [
        "HTTP/3 server integration — quinn/h3 infrastructure and router present, endpoint handlers incomplete"
      ],
      "planned": [
        "Cross-network CA federation — inter-node CT log sync and multi-CA trust",
        "Threshold cryptography — Shamir's Secret Sharing for distributed CA signing authority",
        "Automated certificate rotation scheduler (config field exists, logic not implemented)",
        "OCSP responder and CRL distribution (revocation currently store-only)"
      ]
    },
    "completion": 71
  },
  {
    "id": "ui",
    "name": "HyperMesh UI",
    "description": "React dashboard for HyperMesh ecosystem monitoring and management",
    "phase": "alpha",
    "features": {
      "working": [
        "Dashboard home with ecosystem overview",
        "Module pages (STOQ, TrustChain, Catalog, Caesar, NGauge, HyperMesh)",
        "Component library (Radix UI primitives, Tailwind 4)",
        "Chart system (Line, Bar, Pie, Area, Gauge, Sparkline, Topology, Network)",
        "TrustChain management (certificates, security, consensus, node config)",
        "Asset management views (creation wizard, advanced management)",
        "Proxy and NAT address management",
        "API status monitoring and performance dashboards",
        "Global search across ecosystem modules",
        "Storybook component documentation (5 stories)",
        "Accessibility wrappers and keyboard navigation",
        "React Router page routing with sidebar navigation"
      ],
      "inDevelopment": [
        "E2E test suite (Playwright, 2 specs)",
        "STOQ native demo (WebAssembly integration)",
        "Integration test harness page",
        "Component unit tests (Vitest, 3 test files)"
      ],
      "planned": [
        "Live STOQ WebSocket data connections",
        "Real-time metrics streaming",
        "Multi-node cluster topology visualization",
        "Security monitoring with live alerts",
        "Native desktop dashboard (Tauri cross-platform: Linux/macOS/Windows)",
        "Caesar wallet and transaction management UI",
        "NGauge analytics and reward distribution dashboard"
      ]
    },
    "completion": 52
  }
];
