// AUTO-GENERATED by scripts/sync-status.ts
// DO NOT EDIT - derived from codebase metrics

export interface CrateStats {
  id: string;
  files: number;
  linesOfCode: number;
  testCount: number;
}

export const crateStats: CrateStats[] = [
  {
    "id": "block-matrix",
    "files": 404,
    "linesOfCode": 139656,
    "testCount": 810
  },
  {
    "id": "caesar",
    "files": 37,
    "linesOfCode": 12753,
    "testCount": 220
  },
  {
    "id": "caesar-sdk",
    "files": 5,
    "linesOfCode": 1039,
    "testCount": 2
  },
  {
    "id": "catalog",
    "files": 78,
    "linesOfCode": 28372,
    "testCount": 52
  },
  {
    "id": "engauge",
    "files": 21,
    "linesOfCode": 5567,
    "testCount": 130
  },
  {
    "id": "gateway",
    "files": 24,
    "linesOfCode": 7040,
    "testCount": 155
  },
  {
    "id": "hypermesh-ebpf",
    "files": 11,
    "linesOfCode": 8073,
    "testCount": 152
  },
  {
    "id": "hypermesh-lib",
    "files": 11,
    "linesOfCode": 2955,
    "testCount": 97
  },
  {
    "id": "stoq",
    "files": 60,
    "linesOfCode": 17911,
    "testCount": 145
  },
  {
    "id": "trustchain",
    "files": 91,
    "linesOfCode": 34093,
    "testCount": 96
  },
  {
    "id": "ui",
    "files": 266,
    "linesOfCode": 42534,
    "testCount": 5
  }
];

export const totalStats = {
  "totalFiles": 1008,
  "totalLines": 299993,
  "totalTests": 1864,
  "crateCount": 11
};
