// AUTO-GENERATED by scripts/sync-status.ts
// DO NOT EDIT - update crate-status.toml files instead

export interface CrateStatus {
  id: string;
  name: string;
  description: string;
  phase: "planning" | "alpha" | "beta" | "stable";
  features: {
    working: string[];
    inDevelopment: string[];
    planned: string[];
  };
  completion: number;
}

export const crateStatuses: CrateStatus[] = [
  {
    "id": "block-matrix",
    "name": "Block-MATRIX",
    "description": "3D mesh topology, matrix-aware distributed computing, and asset pipeline",
    "phase": "alpha",
    "features": {
      "working": [
        "3D coordinate system (x,y,z positioning)",
        "Tensor math library (Vector3D, Matrix3x3, A*)",
        "Every-node blockchain (independent chains)",
        "Geospatial module (GPS conversion, clustering)",
        "Asset adapters (CPU/GPU/Memory/Storage/Network/Container)",
        "Privacy allocation (PrivacyMode: Anonymous/Private/Public)",
        "Matrix persistence (WAL, snapshots, recovery)",
        "Proof of State four-proof validation",
        "eBPF security manager with XDP attachment and policy enforcement",
        "ExtensionValidator for HyperMesh headers (PoS, asset hash, routing, privacy)",
        "Security integration framework (eBPF manager, syscall tracing, metrics collection)",
        "Privacy-eBPF bridge (PrivacyEbpfBridge tier updates, flexibility matrix, sync_to_kernel)",
        "Asset pipeline (Compress->Encrypt(Kyber-1024)->Shard->Distribute, adaptive RS parameters by asset size)",
        "Cross-scope proxy routing (ScopeAwareRouter, gateway node selection, encryption enforcement)",
        "Tensor operations for cross-network transaction routing (TransactionRouter, scope-aware pathfinding, relay optimization)",
        "CLI for matrix topology queries, node management, and asset operations (CommandExecutor, CliOutput, 34 tests)",
        "Container runtime with process isolation (ProcessIsolation, real spawn/stop/resource tracking, 15 tests)",
        "Cross-platform node binary (OsAbstraction for Linux/macOS/BSD/Windows, PlatformInfo, hardware detection, 62 tests)",
        "BLAKE3 content hashing (whitepaper-aligned)",
        "Capability-based GPU detection (honest fallback, no fake hardware)",
        "StateAuthenticator trait (renamed from ConsensusValidator)",
        "Shard commitment (BLAKE3 hash anchoring blocks to spatial shard evidence)",
        "PoSPing spatial verification (epoch-seeded bilateral probes, scope-gated, binary result)",
        "IPv6 asset addressing (AssetAddress: fd48:4d00 prefix, matrix coords, content fingerprint, shard sub-addressing)",
        "Asset transfer protocol (TransferEngine, StateProofBytes, PoS-authenticated transfers with blockchain receipts)",
        "10-node transfer simulation (helix topology, sequential chain transfers, fingerprint preservation, 6 tests)",
        "Node bootstrap lifecycle (genesis block, self-signed cert, DNS init)",
        "Real hardware metrics collection (CPU/memory/network/storage from /proc)",
        "PeerIdentity bridges to lib NodeId (to_node_id(), From<&ScopedIdentity>)",
        "NodeFingerprint From<NodeId> conversion (same 32-byte concept)",
        "NetworkScope::from_identity() for scope-aware asset access",
        "Genesis capability assessment (R1, R10 — GenesisAssessor: hardware probe -> GenesisAssetRecord per resource with IPv6 addressing)",
        "Asset blockchain registration (register_asset_record creates block, validates PoS, appends to chain)",
        "Automatic shard commitment in block production (R12 — BLAKE3(sorted placements) computed and set on block)",
        "Distribution audit trail (record_to_blockchain, verify_placement, query_audit_trail — real BLAKE3-based ledger)",
        "Adaptive erasure coding (R14 — ErasureCodingParams::for_asset_size wired into pipeline, scales RS with asset size)",
        "Network trust layer (BLAKE3 crypto for p2p/federated/public, NodeId-based auth, PrivacyMode-aware trust)",
        "ShardTransport trait (send_shard/fetch_shard/is_reachable, MockShardTransport for testing)",
        "Instruction-based retrieval with ShardTransport integration (fetch_from_location wired to trait)",
        "mDNS peer discovery (PeerAnnouncement, multicast protocol on _hypermesh._udp.local)",
        "Gossip protocol for mesh coordination (GossipState, membership tracking, configurable fanout/interval)",
        "Full retrieval pipeline via ShardTransport (retrieve_asset: fetch → RS reconstruct → decrypt → decompress)",
        "Network scope sync wired to BlockTransport (TransportSyncDriver: reflector discovery, block propagation, state update)",
        "Dynamic shard rebalancing with real transport (execute_actions_via_transport: move/replicate shards via ShardTransport)",
        "Swarm distribution protocol (R12 — SwarmProtocol: announce/discover/serve, cascade providers, O(log N) per-node load)",
        "Streaming shard reconstruction (R13 — StreamingReconstructor: incremental per-group RS decode, memory-efficient)",
        "Shard migration (R14 — MigrationExecutor: copy-then-redirect, non-blocking reads, rollback on failure)",
        "Privacy-scoped dedup verification (R4 — PrivacyScopedDedup: full tracking Device/Private, hash-only Anonymous, tamper detection)",
        "Min-spec validation (R13 — MinSpecValidator: 1Mb/s bandwidth, 50GB storage, 4GB RAM, 2-core budget checks)",
        "Gateway cross-scope transfers wired to ShardTransport (Lock→Transfer→Unlock with real shard movement)",
        "Multi-node deployment wired to gossip+transport (ClusterTransportBridge: sync_from_gossip, probe_health via ShardTransport)",
        "Service mesh load balancer (MeshLoadBalancer: RoundRobin + LeastConnections, health-aware endpoint filtering)",
        "User contribution distribution bridge (ContributionDistributionBridge: wired to SwarmProtocol for announce/serve shards)",
        "Intelligence metrics bridge (IntelligenceMetricsCollector: real /proc CPU/memory via hardware module, processing stats)",
        "Performance monitoring integration (MonitoringIntegration with record/flush, AlertingManager with threshold breach detection)",
        "Performance regression prevention (RegressionDetector: baseline comparison, per-metric tolerance, configurable alerts)",
        "1M-node stress test simulation (R12, R13 — cascade O(log N) verification, min-spec budget validation, shard commitment scaling)",
        "Node bootstrap Anonymous certificate strategy (select_certificate_strategy routes by PrivacyMode)",
        "Internal DNS service registration (LOCAL_SERVICES table, 5 services registered at boot, resolve_service())",
        "Blockchain state persistence on restart (PersistenceManager wired to bootstrap, genesis/blocks/cert survive reboot)",
        "NodeBlockchain::from_blocks() — reconstruct in-memory chain from persisted blocks with integrity validation",
        "Node resume path (NodeBootstrap::resume() loads persisted state instead of creating fresh genesis)"
      ],
      "inDevelopment": [
        "Reflector bootstrap mode — first node at trust.hypermesh.online acts as peer discovery reflector for joining nodes"
      ],
      "planned": []
    },
    "completion": 98
  },
  {
    "id": "caesar",
    "name": "Caesar",
    "description": "Gold-denominated Ephemeral Value Protocol for HyperMesh",
    "phase": "alpha",
    "features": {
      "working": [
        "EVP core types (PacketId, GoldGrams, MarketTier, PacketState with 11 states, DemurrageRate)",
        "CaesPacket state machine (Minted→InTransit→Delivered→Settling→Settled, plus Hold/Stall/Expire/Refund/Dissolve/Disperse)",
        "Tier-based demurrage decay (L0 ~5%/hr, L1 ~0.1%/day, L2 ~0.01%/day, L3 ~0.001%/day)",
        "Governor PID controller (velocity, gold deviation, volume, liquidity, in-transit float)",
        "Constitutional fee caps (L0=5%, L1=2%, L2=0.5%, L3=0.1%)",
        "Per-tier fee modifiers and demurrage overrides",
        "Network pressure classification (6 quadrants: Bubble, Crash, Stagnation, GoldenEra, Bottleneck, Vacuum)",
        "Universal Payment Interface — IngressAdapter + EgressAdapter traits with 4 finality types",
        "Settlement protocol — validate_settlement, settle_packet, split_rewards (80/20 egress/transit)",
        "Acceptance criteria — per-recipient tier/adapter/fee/delegate preferences on Network chain",
        "Gravity dissolution — 90-day timeout, 6-criteria qualification, weighted shard-holder distribution",
        "Packet processor — validate, handoff with hop/fee tracking, batch processing",
        "Fee distribution — 80/20 egress/transit split, bytes-weighted transit allocation",
        "Gold oracle — price tracking, 10% band validation, grams↔USD conversion",
        "Effective price composite (whitepaper §5.1: network fees + speculation pressure - liquidity shadow)",
        "Capacity-based packet routing (bandwidth/buffer/latency/load scoring, no trust/reputation)",
        "Holding buffer — orbit buffer for fee-budget-exceeded/congestion packets with retry limits",
        "Packet-centric storage (PacketRecord, SettlementRecord, metrics, JSON persistence)",
        "CaesarProtocol coordinator (storage + processor + distributor + oracle + router + governor)",
        "Conservation law verification + circuit breaker (whitepaper §3.1)",
        "MeshCredit UPI adapter (internal BlockMatrix ledger, 1:1 CAES denomination)",
        "Settlement execution pipeline (validate → egress adapter → fee distribution → conservation check)",
        "Dispersed state handling (egress failure → holding buffer → retry settlement)",
        "Node operator preferences integration with routing (tier weights, value range, auto_mode)",
        "Governor-adjusted routing fees (PID-driven fee calculation per packet)",
        "OracleFeed trait for pluggable gold price sources (ManualFeed for alpha)",
        "Node status tracking in storage (settled count, fee earnings)",
        "STOQ API handlers wired to real CaesarProtocol (route_packet, node_status, governor_params, effective_rate, health)",
        "Engauge capacity metrics integration (feature-gated: fee distribution, Governor throttle, routing)",
        "Caesar binary entry point — STOQ API server launcher (caesar/src/bin/caesar.rs)",
        "caesar.hypermesh.online gateway routing rule (gateway/src/router.rs + config.rs)",
        "Caesar CLI — packet operations + node management (commands, executor, output modules)",
        "Caesar SDK — UPI traits (IngressAdapter + EgressAdapter) + MeshCreditAdapter extracted into reusable crate",
        "Cross-chain bridge (ChainBridge trait, InternalBridge with conservation checks, MockChainBridge for testing)"
      ],
      "inDevelopment": [],
      "planned": [
        "Live multi-chain UPI bridge BTC/ETH/SOL (blocked by: chain SDK deps — ethers-rs/bitcoin/solana-sdk + bridge liquidity model)",
        "External fiat/crypto payment rail integrations — Stripe, Plaid, OpenBanking, Square adapters (blocked by: external API keys + OAuth2 flows + PSD2/PCI-DSS compliance + Gateway outbound HTTP proxy)"
      ]
    },
    "completion": 94
  },
  {
    "id": "caesar-sdk",
    "name": "Caesar SDK",
    "description": "Universal Payment Interface SDK — adapter traits for external payment rail integration",
    "phase": "alpha",
    "features": {
      "working": [
        "IngressAdapter trait (7 methods: adapter_id, supported_denominations, lock_external_value, verify_lock, release_lock, liquidity_pressure, to_gold_grams)",
        "EgressAdapter trait (5 methods: adapter_id, supported_denominations, available_capacity, settle, capacity_ratio)",
        "UPI shared types (IngressLockProof, SettlementReceipt, SettlementFinality, LiquidityPressure, UpiError)",
        "MeshCreditAdapter reference implementation (internal BlockMatrix ledger, 1:1 CAES denomination)",
        "MockIngressAdapter + MockEgressAdapter (public test utilities for adapter developers)"
      ],
      "inDevelopment": [],
      "planned": [
        "Adapter development guide and examples"
      ]
    },
    "completion": 83
  },
  {
    "id": "catalog",
    "name": "Catalog",
    "description": "Asset package registry and template library",
    "phase": "alpha",
    "features": {
      "working": [
        "Asset package types and metadata",
        "Asset registry with typedef registration and search (legacy publish/install are migration stubs)",
        "Template generation framework",
        "Semantic versioning",
        "Scripting engine (syntax validation)",
        "STOQ transport for distribution",
        "TrustChain security integration (FALCON-1024 cert lifecycle)",
        "Proof of State validation for packages",
        "Asset SDK (clean public API facade)",
        "Typedef registry marketplace (browsing, multi-factor search scoring, featured listings)",
        "Caesar contribution reward integration (CatalogRewardAdapter, ContributionTracker)",
        "catalog.hypermesh.online STOQ API endpoint (browse/search/package/publisher/stats/health)",
        "Binary publisher authentication (whitepaper-aligned, no reputation scoring)",
        "BLAKE3 content hashing (whitepaper-aligned)",
        "DHT distribution — local data structures (XOR-distance routing table, k-bucket management, stale eviction, value store; remote node I/O pending STOQ transport wiring)",
        "Dependency resolution (topological sort, transitive resolution, circular dependency detection, conflict detection)",
        "Asset validation pipeline (size limits, BLAKE3 hash verification, metadata completeness, type-specific: WASM magic bytes, JSON parse)",
        "Peer-to-peer sharing wired to DHT (announce via BLAKE3 key, discover with text search fallback; local-only until DHT remote I/O is wired)",
        "HyperMesh execution delegation (allocate/query/terminate lifecycle, resource validation, status tracking)"
      ],
      "inDevelopment": [
        "Catalog server binary — standalone STOQ API server (catalog.hypermesh.online) with browse/search/publish/install endpoints",
        "DHT remote I/O — wire store_value_on_node/query_value_from_node to real STOQ transport for cross-node package discovery",
        "Shared asset library — browse and install packages across nodes on the public network"
      ],
      "planned": []
    },
    "completion": 86
  },
  {
    "id": "engauge",
    "name": "engauge",
    "description": "Work tracking, content receipts, capacity metrics, and network analytics for HyperMesh",
    "phase": "alpha",
    "features": {
      "working": [
        "Content receipts (BLAKE3 hash + timestamp + node signature, receipt bundles, verification)",
        "Metrics collector (compute cycles, bandwidth, latency, receipt density, activity scoring)",
        "KYC compliance checker (self-sovereign attestation on Device chain, tier-based levels)",
        "Organic vs speculative traffic detection (pattern-based aggregate flow analysis, whitepaper §16.5)",
        "Governor throttle signal (activity score, band modifier, demurrage modifier, organic ratio feedback)",
        "Capacity metrics (bytes served, compute delivered, storage, bandwidth, uptime — no trust/reputation)",
        "Multi-epoch capacity aggregation and trending (EpochTracker, CapacityTrend, AggregatedCapacity)",
        "Metrics streaming protocol (MetricsFrame, 4 payload types, encode/decode, privacy-mode-aware)",
        "Differential privacy filter (Laplace noise injection, epsilon-calibrated, Anonymous/Private/Public)",
        "Metrics publisher and subscriber (push model, per-source rolling window, sequence tracking)",
        "Regional aggregator (multi-node metrics aggregation for routing decisions)",
        "Routing intelligence (TensorWeightModifier, PathPolicyRecommendation, RoutingAdvisor + PathAdvisor traits)",
        "Resource pool and lease contracts (sovereign allocation percentages, time-bounded leases, BlockMatrix asset integration)",
        "Lease manager (supply/demand matching, validation, lifecycle management — Proposed→Active→Completed)",
        "Pricing engine (Governor-adjusted, tier-aware multipliers L0=1.0/L1=0.8/L2=0.5/L3=0.2, supply-demand scoring)",
        "Content push manager (opt-in/out recipients, publisher registration, fee-based anti-spam)",
        "STOQ METRICS frame type integration (0xfe000007 custom frame, feature-gated in stoq crate)",
        "Verification metrics streaming (PoSPing results via MetricsFrame, privacy-filtered, regional aggregation)",
        "Self vs network metrics separation (SelfMetrics, PeerMetrics, node_metrics module, capacity assessment)",
        "EconomicSnapshot extended fields (holdings_by_tier, fee_rate, in_transit count)",
        "Real network metrics collection (MetricsSource trait, SystemMetricsSource /proc readers, MockMetricsSource for tests)",
        "Real metrics ingestion pipeline (route by payload type, differential privacy filter, time-series storage)",
        "Swarm analytics R12 (ShardPopularity, SwarmAnalytics: record_request, get_popular_shards, demand maps)",
        "Replication triggers R12 (ReplicationTrigger: demand vs replica threshold, ReplicationSignal with urgency)",
        "Dispersion intelligence R12 (DispersionAdvisor: k-means clustering, recommend_placement near demand)",
        "Swarm cascade metrics R12+R13 (CascadeTracker: per-node relay load, propagation speed, bottleneck detection)",
        "Min-spec performance profiling R13 (MinSpecProfiler: 256MB/5%CPU/10KB/s budget validation)",
        "Real-time routing intelligence feed (RoutingIntelFeed: subscribe/publish RoutingUpdate to STOQ)",
        "Caesar in-transit/holding amount tracking (CaesarTracker: per-node economic state, network snapshots)",
        "Collective network intelligence (CollectiveIntelligence: privacy-aware aggregation, 4 NetworkInsight types)",
        "STOQ-compatible API server (EngaugeStoqApi: 6 handlers, quinn-based QUIC, bind [::1]:9296, feature-gated server binary)"
      ],
      "inDevelopment": [],
      "planned": []
    },
    "completion": 100
  },
  {
    "id": "gateway",
    "name": "Gateway",
    "description": "HTTP/3 + STOQ gateway for *.hypermesh.online — 4 roles: bootstrap, inbound proxy, outbound proxy, inter-network",
    "phase": "alpha",
    "features": {
      "working": [
        "QUIC/HTTP3 server setup (quinn + h3)",
        "TLS provider (File/TrustChain/SelfSigned certificate sources)",
        "Connection pool with health checks",
        "Router with path-based backend selection",
        "Circuit breaker and retry logic",
        "CORS middleware and request logging",
        "Request handling (h3 0.0.8 RequestResolver API)",
        "HTTP/3 backend proxying",
        "STOQ protocol bridge (dual-listener HTTP/3 + STOQ)",
        "STOQ listener with exponential backoff",
        "Bootstrap token flow (HTTP/3 to STOQ transition)",
        "PoS authentication and session management",
        "Cross-scope routing (Device/Network via ScopeRouter)",
        "Federation bridge with trust levels (Full/Conditional/Untrusted)",
        "Cross-scope transfer proxy (lock/transfer/unlock lifecycle)",
        "Rate limiting and DDoS protection (token bucket per-IP/identity/global)",
        "Load balancing (RoundRobin/LeastConnections/WeightedRoundRobin/HealthAware)",
        "Multi-domain SNI routing (*.hypermesh.online wildcard support)",
        "Outbound proxy with allowlist filtering",
        "Inbound proxy for HyperMesh dashboards (dashboard/engauge/caesar/catalog)",
        "Engauge backend routing (config: engauge_addr/server_name, env vars, SNI routing via inbound proxy)"
      ],
      "inDevelopment": [
        "Production config loader — TOML/env-based config for listen addresses, cert paths, backend service addresses, rate limits",
        "Backend service discovery — resolve trustchain/blockmatrix/caesar/catalog backends by address or service registry",
        "Health check aggregation — /health endpoint that checks all backend services and reports overall status"
      ],
      "planned": []
    },
    "completion": 88
  },
  {
    "id": "hypermesh",
    "name": "HyperMesh Repository",
    "description": "Cross-cutting repository-wide milestones and meta-tasks",
    "phase": "alpha",
    "features": {
      "working": [
        "Refactor / consolidation — removed Docker/Terraform/K8s/CloudFormation (system-level daemon model), fixed CI workflows, workspace lint config",
        "Documentation 100% correct — all 11 crate READMEs, ARCHITECTURE.md, root README accurate with correct stats, models, and IPv6 coverage",
        "Benchmarks — Criterion benchmarks for blockmatrix (5: phase1, retrieval, transfer, tensor, basic), stoq (3: throughput, real_throughput, ebpf), trustchain (certificates)",
        "Full development/contributions pipeline — CONTRIBUTING.md, SECURITY.md, CHANGELOG.md, pre-commit hooks, PR workflow documented",
        "Bug tracking/reporting — GitHub issue templates (bug report, feature request), severity labels, security disclosure via SECURITY.md",
        "Cross-crate integration tests — 33 compile-time tests in cross_crate_integration.rs + 17 integration tests (asset_pipeline, blockchain_scope, privacy_consistency)",
        "Unified cross-crate identity model (NodeId BLAKE3([u8;32]), ScopedIdentity, WorkloadType — all crates use lib canonical types)",
        "Scope-aware identity system (IdentityScope respects Device|Network scope + traceability axis, cert extensions, strategy scoping)",
        "Certificate lifecycle per scope (Anonymous=ephemeral minutes, Private=bounded days, Public=full months — trustchain + stoq)"
      ],
      "inDevelopment": [
        "Live alpha deployment — trust.hypermesh.online first public node (gateway + trustchain CA/DNS/CT + blockmatrix reflector)",
        "Network MVP — peer discovery, shard transport over QUIC, end-to-end asset store/fetch across nodes",
        "Systemd unit fixes — correct binary names, port assignments, working directory setup",
        "Port allocation plan — resolve 8446 conflict between trustchain API and blockmatrix, assign unique ports per service"
      ],
      "planned": [
        "Modular restructure for polyrepo/microservice — extract crates into independent repos with CI, versioned APIs, and publish pipeline",
        "Development documentation live sync — auto-generate and publish docs from source (rustdoc, typedoc) on every merge",
        "Website linking restructure to polyrepo and live docs — update hypermesh.online to link per-repo docs, changelogs, and dashboards",
        "Usability testing — real-user testing of CLI, dashboard, and asset workflows with feedback collection and iteration",
        "Remove all hardcoded performance stubs (tests/performance.rs, tests/validation.rs, tests/chaos.rs)",
        "Real partition/chaos testing framework"
      ]
    },
    "completion": 47
  },
  {
    "id": "hypermesh-ebpf",
    "name": "HyperMesh eBPF",
    "description": "Unified eBPF intelligence layer - single source of truth for all packet processing",
    "phase": "alpha",
    "features": {
      "working": [
        "HyperMeshEbpf orchestrator API — capability detection, state management, graceful degradation (Full eBPF+AF_XDP → eBPF only → userspace)",
        "AF_XDP zero-copy I/O — 4-ring UMEM buffers, frame allocator, batch send/receive via syscalls",
        "C kernel XDP programs — counter, kprobe, tracepoint, HyperMesh XDP with extension header parsing (magic 0x484D)",
        "AF_XDP kernel integration — xsk_map redirect, UMEM mmap lifecycle, socket reuse across send/receive paths",
        "BPF map policy enforcement — policy/PoS/asset/xsk maps with 32-byte LE serialization and sync_to_kernel",
        "PacketDecision three-path routing — Pass (local), Redirect (AF_XDP→STOQ), Forward (XDP_TX to matrix node), Drop",
        "PoS pre-validation pipeline — header parsing, algorithm indicators, difficulty checks, FastValidationResult",
        "Validation hooks — STOQ (certificate, packet) + BlockMatrix (extension) registered via set_validation_hooks()",
        "Asset hash verification (BLAKE3) and blockchain registry validation",
        "Matrix routing path validation (IPv6 + matrix position encoding)",
        "Privacy tier eBPF enforcement with per-policy flag control",
        "Orchestrator state storage — routing rules, asset hashes, PoS validation state persisted across sessions",
        "build.rs auto-compilation of C eBPF programs (ebpf-loader feature gate)",
        "Unified intelligence + transport metrics collection",
        "Multi-queue AF_XDP load balancing — RoundRobin/LeastLoaded/FlowHash strategies, QueueMetrics, MultiQueueManager orchestrator",
        "Kernel-space PoS structural validation — difficulty (leading zero bits), algorithm indicator, TTL-based cache expiry; full crypto (FALCON-1024/Ed25519/ECDSA) validated in userspace cache model",
        "Hardware offload detection and opportunistic NIC offload — driver detection (mlx5_core/nfp/bnxt_en), OffloadPolicy (Disabled/Opportunistic/Required), automatic fallback to native XDP"
      ],
      "inDevelopment": [],
      "planned": []
    },
    "completion": 100
  },
  {
    "id": "hypermesh-lib",
    "name": "HyperMesh Lib",
    "description": "Shared canonical types for the HyperMesh ecosystem",
    "phase": "alpha",
    "features": {
      "working": [
        "NodeId, AssetId, NetworkId, and ContentHash newtypes",
        "PrivacyMode struct (2-axis: AccessScope + tracked)",
        "BlockchainScope enum (Device | Network)",
        "ProofType enum (PoSpace/PoStake/PoWork/PoTime)",
        "MatrixPosition coordinate type",
        "PipelineStage enum",
        "CryptoAlgorithm enum (Falcon/Kyber/AES)",
        "HypermeshError unified error type",
        "Three-pillar asset system (AssetKind + BaseState/AssetStatusTrait + AssetAdapter)",
        "Canonical consensus proof types (SpaceProof/StakeProof/WorkProof/TimeProof/ProofOfState + Validatable trait)",
        "EVP economic types (PacketId, GoldGrams, MarketTier, PacketState, DemurrageRate)",
        "KeyPairId and AssetMetadata structs",
        "AssetAddress IPv6 type (fd48:4d00 prefix, matrix coords, content fingerprint, shard sub-addressing)",
        "Transmission asset type in SystemAssetKind (R10 — first-class mesh relay bandwidth asset)",
        "ErasureCodingParams with adaptive shard sizing (R14 — for_asset_size scales RS parameters)",
        "HardwareCapabilities with minimum spec enforcement (R1/R13 — meets_minimum_spec validation)",
        "BLAKE3 validation helpers (validate_blake3_hash, compute_blake3_hash for R4)",
        "AssetMetadata canonical struct in lib (consolidated definition with AssetKind + state + timestamps)",
        "Dns and Transmission variants added to blockmatrix BaseSystemType",
        "VirtualMachine and Library removed from blockmatrix AssetType/BaseSystemType",
        "Trustchain proof types linked to lib canonical ProofType (proof_type() methods)",
        "Trustchain NodeId/AssetId renamed to AuthenticatedNode/AuthenticatedAsset (use lib newtypes)",
        "AssetMetadata consolidated (crate-local copies renamed: PipelineInputMetadata, PackageSpecMetadata, etc.)",
        "PacketId conflict resolved (blockmatrix network isolation uses IsolationPacketId)",
        "ShardCommitment type (R12 — BLAKE3(sorted placements) compute/verify API)",
        "Genesis asset inventory types (R1 — Cpu/Gpu/Storage/Network/Memory capability structs)",
        "GenesisAssetRecord type (R1+R10 — sovereign genesis with hardware-assessed IPv6 assets)",
        "Shared serialization via postcard (encode/decode/encode_bounded + EncodingError)",
        "Unified NodeId type (BLAKE3([u8;32]) from FALCON-1024 pubkey, replaces opaque String)",
        "Scope-aware identity types (WorkloadType, IdentityScope, ScopedIdentity — respects BlockchainScope + traceability axis)",
        "Cross-crate validation helpers (validate_node_id, validate_content_hash, validate_matrix_position, validate_privacy_mode)",
        "Runtime state types (NodeState, NetworkState, SyncStatus, RuntimeAssetState, RuntimeSnapshot)",
        "Common test utilities (test_node_id, test_asset_id, test_content_hash, test_privacy_mode, TestFixtures)",
        "Public SDK types (SdkCapabilities, AssetDescriptor, NodeDescriptor, QueryResult<T>)"
      ],
      "inDevelopment": [],
      "planned": []
    },
    "completion": 100
  },
  {
    "id": "stoq",
    "name": "STOQ Protocol",
    "description": "QUIC-based transport protocol with eBPF acceleration and FALCON-1024 signing",
    "phase": "alpha",
    "features": {
      "working": [
        "QUIC/IPv6 transport — connection pooling, health checks, adaptive congestion control",
        "FALCON-1024 crypto — key generation, signing, dynamic key_id, real signature verification via FalconTrustChainClient",
        "Certificate management — two modes: Anonymous (ephemeral per-connection, no CA/CT) and Authenticated (TrustChain-issued, endpoint is configuration for Private/Federated/Public)",
        "Network isolation — PrivacyMode (Anonymous/Private/Public) with eBPF policy push and tunnel traffic type enforcement",
        "eBPF-accelerated send/receive — AF_XDP zero-copy I/O via StoqEbpfTransport thin consumer wrapper",
        "eBPF validation hooks — CertificateValidator + PacketValidator registered with hypermesh-ebpf orchestrator",
        "Kernel eBPF program loading via hypermesh-ebpf ebpf-loader feature gate",
        "Protocol extensions — packets, tokens, shards with canonical length-prefixed serialization",
        "PoS/PoW validation — hash-meets-difficulty checks, results fed to eBPF policy layer",
        "Matrix-aware positioning via hypermesh_lib canonical types",
        "Adaptive transport tiers — EWMA bandwidth estimation, MTU discovery, loss-based adjustment, CC selection per tier + MinSpec for R13",
        "Protocol-level PoS token validation at line rate — two-stage fast/full, privacy-tier-aware, cached, rate-limited",
        "Multi-path QUIC — scope/privacy/federation policy enforcement, bandwidth-weighted scheduling, redundant mode",
        "Reflector pool transport — heartbeat/health tracking, quorum detection, sync protocol, MatrixMessage bridge",
        "Engauge METRICS frame type (0xfe000007) — feature-gated handler for streaming MetricsFrame payloads",
        "BLAKE3 content hashing (whitepaper-aligned)",
        "Real transport metrics (LatencyTracker with jitter, TransportSnapshot, per-connection stats)",
        "Identity-aware connection establishment (extract_node_id from X.509 SPKI, identity_scope per strategy)",
        "Certificate manager with real X.509 validation (replaced placeholder private key)",
        "Certificate store persistence across restarts (filesystem cache ~/.stoq/certs/)",
        "Graceful degradation with expired certificates (fallback to self-signed Anonymous)",
        "Permission enforcement at protocol layer (EKU-based scope checking per operation)",
        "Service discovery registry (register/resolve/deregister by service type)",
        "Cipher suite negotiation for Private/Anonymous networks (R8 — CipherSuitePolicy, negotiate handshake)",
        "MetricsFrame protocol wiring to engauge (MetricsFrameBridge: transport snapshot → Capacity/Congestion/Routing frames)",
        "Min-spec transport validation (R13 — TransportMinSpec: connection budget, bandwidth checks, 1Mb/s/4GB/2-core limits)"
      ],
      "inDevelopment": [
        "StoqShardTransport — real ShardTransport impl over QUIC (send_shard/fetch_shard/is_reachable via StoqTransport connections)",
        "Peer connection manager — maintain persistent QUIC connections to known peers, reconnect on failure"
      ],
      "planned": [
        "Real jitter benchmarking under controlled partitions",
        "Partition recovery timing measurements"
      ]
    },
    "completion": 87
  },
  {
    "id": "trustchain",
    "name": "TrustChain",
    "description": "FALCON-1024 Certificate Authority with Proof of State validation",
    "phase": "alpha",
    "features": {
      "working": [
        "FALCON-1024 post-quantum signing",
        "Kyber-1024 key encapsulation",
        "Proof of State four-proof validation",
        "Security monitoring and Byzantine detection",
        "DNS resolver (programmatic resolution works, HTTP/3 endpoint wired, STOQ transport client not fully integrated)",
        "STOQ-based API server",
        "SecurityIntegratedCA with mandatory consensus and real metrics",
        "Binary PoS authentication (whitepaper-aligned, no scoring/reputation)",
        "StateAuthenticator (renamed from ConsensusValidator)",
        "BLAKE3 consensus content hashing",
        "OCSP responder with FALCON-1024 signed responses",
        "CRL generator and distributor",
        "Threshold cryptography (Shamir SSS over GF(256))",
        "Deployment quality gates",
        "Cross-network CA federation (peer management, trust levels, FALCON-1024 cross-validation)",
        "CT log federation sync protocol (message types, peer state tracking, consistency proofs)",
        "Anonymous mode ephemeral certificates (Tor-like tunnel certs, no CA/CT)",
        "Certificate rotation (CertificateRotationManager scans store, rotates expiring certs)",
        "Persistent revocation storage (JSON on disk, survives restart)",
        "Canonical ProofType from hypermesh-lib (single source of truth)",
        "Cross-crate identity integration (AuthenticatedNode wraps lib::NodeId, to_scoped_identity() bridge)",
        "Workload identity types (NodeIdentity, ServiceIdentity, AgentIdentity)",
        "Identity-typed certificates (CertificateSubjectType: Node/Service/Agent)",
        "Identity-scoped certificate extensions (IdentityScopeExtension, OID-based, 4-byte encode/decode)",
        "TrustAssetKind includes Transmission variant (R10 alignment with SystemAssetKind)",
        "CA-signed leaf certificates (rcgen signed_by() chain, proper X.509 hierarchy)",
        "Certificate PEM encoding (rcgen .pem() output, proper base64)",
        "Certificate Transparency (Merkle tree with consistency checker, inclusion proofs, cert hash search)",
        "KeyUsage/EKU enforcement in issued X.509 certs (digital signature, key encipherment, server/client auth by subject type)",
        "Threshold crypto integration with CA initialization (Shamir SSS key splitting at startup)",
        "Scope-aware certificates (IdentityScopeExtension embedded via custom OID, Device vs Network scope)",
        "Certificate lifecycle tied to scope (Anonymous=minutes, Private=days, Public=months validity)",
        "Real certificate operation metrics (CAMetrics atomic counters: issued, revoked, validation/issuance latency)",
        "HTTP/3 handlers: list_certificates wired to real cert store",
        "Cascading revocation (parent→child BFS propagation, multi-level cascade)",
        "Distributed revocation propagation (federation broadcast, BLAKE3 integrity, status tracking)",
        "CRL distribution via blockchain (hash-linked blocks, full + delta CRLs, chain integrity verification)",
        "Offline device grace period renewal (scope-dependent: Anonymous=0, Private=7d, Public=30d, max renewals enforced)",
        "Field device bootstrap with intermittent connectivity (Provisional→Enrolling→Enrolled, retry limits)",
        "HTTP/3 handlers wired (consensus_status, consensus_validate with ProofValidation, auth_certificate with CA issuance)",
        "Production DNS zones for catalog.hypermesh.online and engauge.hypermesh.online (addresses + subdomain entries)"
      ],
      "inDevelopment": [
        "Production binary hardening — config file loading, graceful shutdown, health endpoint, signal handling",
        "Let's Encrypt / ACME cert bootstrap for trust.hypermesh.online gateway TLS (initial clearnet bootstrap before self-issued FALCON certs)"
      ],
      "planned": []
    },
    "completion": 95
  },
  {
    "id": "ui",
    "name": "HyperMesh UI",
    "description": "React dashboard for HyperMesh ecosystem monitoring and management",
    "phase": "alpha",
    "features": {
      "working": [
        "Dashboard home with ecosystem overview",
        "Module pages (STOQ, TrustChain, Catalog, Caesar, Engauge, HyperMesh)",
        "Component library (Radix UI primitives, Tailwind 4)",
        "Chart system (Line, Bar, Pie, Area, Gauge, Sparkline, Topology, Network)",
        "TrustChain management (certificates, security, consensus, node config)",
        "Asset management views (creation wizard, advanced management)",
        "Proxy and NAT address management",
        "API status monitoring and performance dashboards",
        "Global search across ecosystem modules",
        "Storybook component documentation (5 stories)",
        "Accessibility wrappers and keyboard navigation",
        "React Router page routing with sidebar navigation",
        "E2E test suite (Playwright, 5 specs: dashboard, navigation, module-pages, accessibility, trustchain)",
        "Integration test harness page"
      ],
      "inDevelopment": [
        "STOQ native demo (WebAssembly integration — StoqWasmClient, useStoqNative hook, wasm stubs)",
        "Component unit tests (Vitest, 3 test files + 3 test utilities = 6 total)",
        "Gateway API client — fetch real data from trust.hypermesh.online gateway endpoints (health, node status, cert status, catalog browse)",
        "Node join flow — UI for connecting to public network (enter bootstrap address, display matrix position, show peer count)",
        "Catalog browser — browse/search/install shared asset packages from catalog.hypermesh.online"
      ],
      "planned": [
        "Live STOQ WebSocket data connections",
        "Real-time metrics streaming",
        "Multi-node cluster topology visualization",
        "Security monitoring with live alerts",
        "Native desktop dashboard (Tauri cross-platform: Linux/macOS/Windows)",
        "Caesar wallet and transaction management UI",
        "Engauge analytics and reward distribution dashboard",
        "Remote device/resource/asset management hub (Tailscale-like C&C for sovereign nodes)",
        "Private network remote access (manage resources across networks from any device)",
        "First-run onboarding flow (sovereign node setup, network join, resource configuration)",
        "New node registration experience (not traditional sign-up — sovereign identity bootstrap)"
      ]
    },
    "completion": 47
  }
];
