// AUTO-GENERATED by scripts/sync-status.ts
// DO NOT EDIT - derived from codebase metrics

export interface CrateStats {
  id: string;
  files: number;
  linesOfCode: number;
  testCount: number;
}

export const crateStats: CrateStats[] = [
  {
    "id": "block-matrix",
    "files": 364,
    "linesOfCode": 129468,
    "testCount": 625
  },
  {
    "id": "caesar",
    "files": 17,
    "linesOfCode": 5654,
    "testCount": 4
  },
  {
    "id": "catalog",
    "files": 57,
    "linesOfCode": 25794,
    "testCount": 41
  },
  {
    "id": "gateway",
    "files": 8,
    "linesOfCode": 1438,
    "testCount": 0
  },
  {
    "id": "hypermesh-ebpf",
    "files": 6,
    "linesOfCode": 1867,
    "testCount": 19
  },
  {
    "id": "hypermesh-lib",
    "files": 4,
    "linesOfCode": 368,
    "testCount": 0
  },
  {
    "id": "stoq",
    "files": 38,
    "linesOfCode": 13977,
    "testCount": 65
  },
  {
    "id": "trustchain",
    "files": 81,
    "linesOfCode": 30027,
    "testCount": 63
  }
];

export const totalStats = {
  "totalFiles": 575,
  "totalLines": 208593,
  "totalTests": 817,
  "crateCount": 8
};
