// AUTO-GENERATED by scripts/sync-status.ts
// DO NOT EDIT - derived from codebase metrics

export interface CrateStats {
  id: string;
  files: number;
  linesOfCode: number;
  testCount: number;
}

export const crateStats: CrateStats[] = [
  {
    "id": "block-matrix",
    "files": 454,
    "linesOfCode": 160834,
    "testCount": 2235
  },
  {
    "id": "caesar",
    "files": 38,
    "linesOfCode": 14259,
    "testCount": 276
  },
  {
    "id": "caesar-sdk",
    "files": 5,
    "linesOfCode": 1030,
    "testCount": 20
  },
  {
    "id": "catalog",
    "files": 83,
    "linesOfCode": 32061,
    "testCount": 306
  },
  {
    "id": "engauge",
    "files": 33,
    "linesOfCode": 11087,
    "testCount": 209
  },
  {
    "id": "gateway",
    "files": 26,
    "linesOfCode": 9406,
    "testCount": 278
  },
  {
    "id": "hypermesh-ebpf",
    "files": 19,
    "linesOfCode": 8235,
    "testCount": 158
  },
  {
    "id": "hypermesh-ffi",
    "files": 17,
    "linesOfCode": 1681,
    "testCount": 12
  },
  {
    "id": "hypermesh-lib",
    "files": 18,
    "linesOfCode": 5842,
    "testCount": 201
  },
  {
    "id": "hypermesh-sdk",
    "files": 13,
    "linesOfCode": 1272,
    "testCount": 27
  },
  {
    "id": "sdk",
    "files": 23,
    "linesOfCode": 1667,
    "testCount": 0
  },
  {
    "id": "stoq",
    "files": 65,
    "linesOfCode": 21964,
    "testCount": 368
  },
  {
    "id": "trustchain",
    "files": 94,
    "linesOfCode": 40554,
    "testCount": 408
  },
  {
    "id": "ui",
    "files": 279,
    "linesOfCode": 45649,
    "testCount": 11
  }
];

export const totalStats = {
  "totalFiles": 1167,
  "totalLines": 355541,
  "totalTests": 4509,
  "crateCount": 14
};
