[package]
name = "hypermesh-consensus"
version = "0.1.0"
edition = "2021"
authors = ["HyperMesh Team"]
description = "HyperMesh Consensus Layer - Raft with Byzantine Fault Tolerance"
license = "MIT OR Apache-2.0"


[lib]
path = "lib.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.38", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Transport layer integration
hypermesh-transport = { path = "../transport" }

# Data structures and concurrency
dashmap = "6.0"
arc-swap = "1.7"
crossbeam = "0.8"
parking_lot = "0.12"

# Collections and indexing
indexmap = "2.2"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
bincode = "1.3"

# Storage engine (LSM-tree implementation) - optional
rocksdb = { version = "0.21", optional = true }
bytes = { version = "1.6", features = ["serde"] }

# Crypto and signatures for Byzantine detection
sha2 = "0.10"
blake3 = "1.5"
ring = "0.16"
ed25519-dalek = { version = "2.1", features = ["serde"] }

# Hex encoding for transaction hash logging
hex = "0.4"

# Time and randomization
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
rand_distr = "0.4"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging and metrics
tracing = "0.1"

# Configuration
config = "0.14"

# UUID generation
uuid = { version = "1.8", features = ["v4", "serde"] }

# HTTP API server for external consensus validation
warp = "0.3"

[dev-dependencies]
tempfile = "3.10"
tokio-test = "0.4"
criterion = { version = "0.5", features = ["async_tokio"] }
proptest = "1.4"

[features]
default = ["monitoring"]
monitoring = []
rocksdb-storage = ["rocksdb"]
benchmark = []

[[bench]]
name = "consensus_benchmarks"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"