[package]
name = "nexus-core-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Core component integration and unit tests for Nexus"

[dependencies]
# Core dependencies
nexus-shared.workspace = true
nexus-transport.workspace = true
nexus-runtime.workspace = true

# Async runtime
tokio.workspace = true
tokio-test.workspace = true
tokio-stream.workspace = true

# Testing frameworks
criterion.workspace = true
proptest.workspace = true
rstest.workspace = true

# Mocking
mockall.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

# Error handling
thiserror.workspace = true
anyhow.workspace = true

# Logging
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-test.workspace = true

# Utilities
chrono.workspace = true
uuid.workspace = true
rand.workspace = true

# Network testing
socket2.workspace = true

# Temporary directories for tests
tempfile = "3.8"

[dev-dependencies]
# Additional test-only dependencies
test-log = "0.2"