// Copyright © 2026 Hypermesh Foundation. All rights reserved.
// Licensed under the Business Source License 1.1.
// See the LICENSE file in the repository root for full license text.

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libs from "./libs";
export type { libs };
export type { OApp } from "./OApp";
export type { OAppCore } from "./OAppCore";
export type { OAppReceiver } from "./OAppReceiver";
export type { OAppSender } from "./OAppSender";
