# Web3 Ecosystem Alert Rules
# Comprehensive alerting for production monitoring

groups:
  # Component availability alerts
  - name: component_availability
    rules:
      - alert: ComponentDown
        expr: up{job=~"trustchain-.*|stoq-.*|hypermesh-.*|catalog-.*|caesar-.*|ngauge-.*"} == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Web3 component {{ $labels.component }} is down"
          description: "{{ $labels.component }} service on {{ $labels.instance }} has been down for more than 1 minute"
          runbook_url: "https://docs.hypermesh.online/runbooks/component-down"
          dashboard: "https://monitoring.hypermesh.online/d/web3-overview"

      - alert: ComponentDegraded
        expr: (up{job=~"trustchain-.*|stoq-.*|hypermesh-.*|catalog-.*|caesar-.*|ngauge-.*"} offset 5m) == 1 and up{job=~"trustchain-.*|stoq-.*|hypermesh-.*|catalog-.*|caesar-.*|ngauge-.*"} == 0
        for: 30s
        labels:
          severity: warning
          category: availability
        annotations:
          summary: "Web3 component {{ $labels.component }} is flapping"
          description: "{{ $labels.component }} service on {{ $labels.instance }} is experiencing intermittent failures"

  # Performance alerts - TrustChain
  - name: trustchain_performance
    rules:
      - alert: TrustChainHighResponseTime
        expr: histogram_quantile(0.95, rate(trustchain_request_duration_seconds_bucket[5m])) * 1000 > 100
        for: 2m
        labels:
          severity: warning
          category: performance
          component: trustchain
        annotations:
          summary: "TrustChain high response time detected"
          description: "TrustChain 95th percentile response time is {{ $value }}ms (threshold: 100ms)"
          current_performance: "35ms typical"
          target_performance: "< 5000ms"

      - alert: TrustChainCertificateIssuanceFailure
        expr: rate(trustchain_certificate_errors_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
          category: security
          component: trustchain
        annotations:
          summary: "TrustChain certificate issuance failures detected"
          description: "Certificate issuance error rate: {{ $value }} errors/second"

      - alert: TrustChainCertificateExpiringSoon
        expr: trustchain_certificate_expiry_days < 30
        for: 0s
        labels:
          severity: warning
          category: security
          component: trustchain
        annotations:
          summary: "TrustChain certificates expiring soon"
          description: "{{ $value }} certificates expire within 30 days"

  # Performance alerts - STOQ
  - name: stoq_performance
    rules:
      - alert: STOQThroughputDegradation
        expr: stoq:throughput_gbps < 2
        for: 2m
        labels:
          severity: critical
          category: performance
          component: stoq
        annotations:
          summary: "STOQ throughput below minimum threshold"
          description: "STOQ throughput is {{ $value }} Gbps (minimum: 2 Gbps)"
          current_performance: "2.95 Gbps"
          target_performance: "40+ Gbps"
          optimization_status: "In progress"

      - alert: STOQConnectionFailures
        expr: rate(stoq_connection_failures_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          category: connectivity
          component: stoq
        annotations:
          summary: "STOQ connection failures detected"
          description: "Connection failure rate: {{ $value }} failures/second"

      - alert: STOQPacketLoss
        expr: stoq_packet_loss_percentage > 1
        for: 1m
        labels:
          severity: warning
          category: performance
          component: stoq
        annotations:
          summary: "STOQ packet loss detected"
          description: "Packet loss rate: {{ $value }}% (threshold: 1%)"

  # Performance alerts - HyperMesh
  - name: hypermesh_performance
    rules:
      - alert: HyperMeshAssetOperationSlow
        expr: histogram_quantile(0.95, rate(hypermesh_asset_operation_duration_seconds_bucket[5m])) * 1000 > 10
        for: 2m
        labels:
          severity: warning
          category: performance
          component: hypermesh
        annotations:
          summary: "HyperMesh asset operations slower than expected"
          description: "95th percentile asset operation time: {{ $value }}ms (typical: 2ms)"
          current_performance: "2ms operations"
          target_performance: "< 1000ms"

      - alert: HyperMeshConsensusFailure
        expr: rate(hypermesh_consensus_failures_total[5m]) > 0
        for: 30s
        labels:
          severity: critical
          category: consensus
          component: hypermesh
        annotations:
          summary: "HyperMesh consensus failures detected"
          description: "Consensus failure rate: {{ $value }} failures/second"

      - alert: HyperMeshAssetValidationFailure
        expr: rate(hypermesh_asset_validation_failures_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          category: validation
          component: hypermesh
        annotations:
          summary: "HyperMesh asset validation failures"
          description: "Asset validation failure rate: {{ $value }} failures/second"

  # Performance alerts - Catalog
  - name: catalog_performance
    rules:
      - alert: CatalogOperationSlow
        expr: histogram_quantile(0.95, rate(catalog_operation_duration_seconds_bucket[5m])) * 1000 > 10
        for: 2m
        labels:
          severity: warning
          category: performance
          component: catalog
        annotations:
          summary: "Catalog operations slower than baseline"
          description: "95th percentile operation time: {{ $value }}ms (baseline: 1.69ms)"
          current_performance: "1.69ms operations"
          target_performance: "< 2000ms"

      - alert: CatalogJuliaVMFailure
        expr: rate(catalog_julia_vm_failures_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          category: execution
          component: catalog
        annotations:
          summary: "Catalog Julia VM execution failures"
          description: "Julia VM failure rate: {{ $value }} failures/second"

      - alert: CatalogAssetCorruption
        expr: catalog_asset_corruption_detected > 0
        for: 0s
        labels:
          severity: critical
          category: data_integrity
          component: catalog
        annotations:
          summary: "Catalog asset corruption detected"
          description: "{{ $value }} corrupted assets detected"

  # Performance alerts - Caesar
  - name: caesar_performance
    rules:
      - alert: CaesarTransactionFailures
        expr: rate(caesar_transaction_failures_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          category: economic
          component: caesar
        annotations:
          summary: "Caesar transaction failures detected"
          description: "Transaction failure rate: {{ $value }} failures/second"

      - alert: CaesarDemurrageCalculationError
        expr: rate(caesar_demurrage_errors_total[5m]) > 0
        for: 30s
        labels:
          severity: critical
          category: economic
          component: caesar
        annotations:
          summary: "Caesar demurrage calculation errors"
          description: "Demurrage calculation error rate: {{ $value }} errors/second"

      - alert: CaesarBlockchainSyncLag
        expr: caesar_blockchain_sync_lag_blocks > 10
        for: 5m
        labels:
          severity: warning
          category: synchronization
          component: caesar
        annotations:
          summary: "Caesar blockchain synchronization lag"
          description: "Blockchain sync lag: {{ $value }} blocks behind"

  # Infrastructure alerts
  - name: infrastructure_health
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage on {{ $labels.instance }} is {{ $value }}%"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage on {{ $labels.instance }} is {{ $value }}%"

      - alert: DiskSpaceLow
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 2m
        labels:
          severity: critical
          category: infrastructure
        annotations:
          summary: "Low disk space detected"
          description: "Disk usage on {{ $labels.instance }} is {{ $value }}%"

      - alert: NetworkThroughputSaturation
        expr: rate(node_network_transmit_bytes_total[5m]) * 8 / 1000000000 > 8
        for: 2m
        labels:
          severity: warning
          category: infrastructure
        annotations:
          summary: "Network throughput saturation"
          description: "Network throughput on {{ $labels.instance }} is {{ $value }} Gbps"

  # Security alerts
  - name: security_monitoring
    rules:
      - alert: UnusualTrafficPattern
        expr: rate(http_requests_total[5m]) > 1000
        for: 2m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Unusual traffic pattern detected"
          description: "Request rate: {{ $value }} requests/second (typical: < 100)"

      - alert: HighErrorRate
        expr: web3:error_rate * 100 > 5
        for: 3m
        labels:
          severity: critical
          category: reliability
        annotations:
          summary: "High error rate detected"
          description: "Error rate for {{ $labels.component }}: {{ $value }}%"

      - alert: FailedAuthenticationAttempts
        expr: rate(authentication_failures_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failure rate: {{ $value }} failures/second"

      - alert: SecurityGroupChanges
        expr: increase(aws_config_security_group_changes_total[5m]) > 0
        for: 0s
        labels:
          severity: warning
          category: security
        annotations:
          summary: "Security group configuration changed"
          description: "{{ $value }} security group changes detected"

  # Business continuity alerts
  - name: business_continuity
    rules:
      - alert: SLAViolation
        expr: web3:component_availability < 0.999
        for: 5m
        labels:
          severity: critical
          category: sla
        annotations:
          summary: "SLA violation: availability below 99.9%"
          description: "Component {{ $labels.component }} availability: {{ $value | humanizePercentage }}"
          sla_target: "99.9% uptime"

      - alert: PerformanceSLAViolation
        expr: web3:response_time_p95 > 1000
        for: 5m
        labels:
          severity: warning
          category: sla
        annotations:
          summary: "Performance SLA violation"
          description: "95th percentile response time: {{ $value }}ms (SLA: < 1000ms)"

      - alert: ThroughputSLAViolation
        expr: web3:throughput_ops_per_second < 100
        for: 5m
        labels:
          severity: warning
          category: sla
        annotations:
          summary: "Throughput SLA violation"
          description: "Current throughput: {{ $value }} ops/second (SLA: > 100 ops/second)"

  # Ecosystem integration alerts
  - name: ecosystem_integration
    rules:
      - alert: ComponentIntegrationFailure
        expr: rate(integration_failures_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          category: integration
        annotations:
          summary: "Component integration failures detected"
          description: "Integration failure rate between {{ $labels.source_component }} and {{ $labels.target_component }}: {{ $value }} failures/second"

      - alert: ConsensusValidationFailure
        expr: rate(consensus_validation_failures_total[5m]) > 0
        for: 1m
        labels:
          severity: critical
          category: consensus
        annotations:
          summary: "Consensus validation failures in ecosystem"
          description: "Cross-component consensus validation failure rate: {{ $value }} failures/second"

      - alert: EcosystemPerformanceDegradation
        expr: avg(web3:response_time_p95) > 500
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Overall ecosystem performance degradation"
          description: "Average 95th percentile response time across ecosystem: {{ $value }}ms"

# Alert routing and escalation
routing_tree:
  # Critical alerts go to PagerDuty immediately
  - match:
      severity: critical
    receiver: pagerduty-critical
    group_wait: 0s
    group_interval: 1m
    repeat_interval: 5m

  # Warning alerts go to Slack
  - match:
      severity: warning
    receiver: slack-warnings
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 30m

  # Performance alerts have special handling
  - match:
      category: performance
    receiver: performance-team
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 15m

  # Security alerts have immediate escalation
  - match:
      category: security
    receiver: security-team
    group_wait: 0s
    group_interval: 1m
    repeat_interval: 5m