name: Phoenix Production CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  RUST_VERSION: '1.75'
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  AWS_REGION: us-east-1

jobs:
  # Quality checks
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Security audit
        run: |
          cargo install cargo-audit
          cargo audit

  # Build and test
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [stable, beta]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          cargo test --all-features --verbose
          cargo test --doc --all-features

      - name: Run benchmarks
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'
        run: cargo bench --all-features --no-fail-fast

  # Build release artifacts
  build:
    name: Build Release
    needs: [quality, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [phoenix-transport, phoenix-certs, phoenix-dashboard, phoenix-cli]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build optimized binary
        run: |
          cargo build --release --package ${{ matrix.component }} --locked
          strip target/release/${{ matrix.component }} || true

      - name: Create archive
        run: |
          tar -czf ${{ matrix.component }}-${{ github.sha }}.tar.gz \
            -C target/release ${{ matrix.component }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.component }}-${{ github.sha }}
          path: ${{ matrix.component }}-${{ github.sha }}.tar.gz
          retention-days: 7

  # Build and push Docker images
  docker:
    name: Build Docker Images
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        component: [phoenix-transport, phoenix-certs, phoenix-dashboard, phoenix-cli]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ matrix.component }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.${{ matrix.component }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Deploy to staging
  deploy-staging:
    name: Deploy to Staging
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'staging'
    environment:
      name: staging
      url: https://staging.phoenix-distributed.com
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name phoenix-staging

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Deploy with Helm
        run: |
          helm upgrade --install phoenix-stack ./infrastructure/helm/phoenix \
            --namespace phoenix-system \
            --create-namespace \
            --set global.environment=staging \
            --set global.version=${{ github.sha }} \
            --set transport.image.tag=${{ github.sha }} \
            --set certificates.image.tag=${{ github.sha }} \
            --set dashboard.image.tag=${{ github.sha }} \
            --set cli.image.tag=${{ github.sha }} \
            --wait \
            --timeout 10m

      - name: Verify deployment
        run: |
          kubectl -n phoenix-system rollout status deployment/phoenix-transport
          kubectl -n phoenix-system rollout status deployment/phoenix-certs
          kubectl -n phoenix-system rollout status deployment/phoenix-dashboard

      - name: Run smoke tests
        run: |
          ./scripts/smoke-tests.sh staging

  # Deploy to production
  deploy-production:
    name: Deploy to Production
    needs: docker
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
    environment:
      name: production
      url: https://phoenix-distributed.com
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name phoenix-production

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy with Helm
        run: |
          helm upgrade --install phoenix-stack ./infrastructure/helm/phoenix \
            --namespace phoenix-system \
            --create-namespace \
            --set global.environment=production \
            --set global.version=${{ steps.version.outputs.VERSION }} \
            --set transport.image.tag=${{ steps.version.outputs.VERSION }} \
            --set certificates.image.tag=${{ steps.version.outputs.VERSION }} \
            --set dashboard.image.tag=${{ steps.version.outputs.VERSION }} \
            --set cli.image.tag=${{ steps.version.outputs.VERSION }} \
            --set transport.replicaCount=5 \
            --set certificates.replicaCount=3 \
            --set dashboard.replicaCount=3 \
            --wait \
            --timeout 15m

      - name: Verify deployment
        run: |
          kubectl -n phoenix-system rollout status deployment/phoenix-transport
          kubectl -n phoenix-system rollout status deployment/phoenix-certs
          kubectl -n phoenix-system rollout status deployment/phoenix-dashboard

      - name: Run smoke tests
        run: |
          ./scripts/smoke-tests.sh production

      - name: Run integration tests
        run: |
          ./scripts/integration-tests.sh production

  # Performance testing
  performance:
    name: Performance Testing
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v4

      - name: Setup test environment
        run: |
          cargo install phoenix-bench
          pip install locust pytest

      - name: Run load tests
        run: |
          ./scripts/load-tests.sh staging

      - name: Run benchmark suite
        run: |
          phoenix-bench --target https://staging.phoenix-distributed.com \
            --duration 300 \
            --connections 1000 \
            --rate 100

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results-${{ github.sha }}
          path: |
            performance-results/
            benchmark-results/

      - name: Comment on PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('performance-results/summary.json', 'utf8');
            const summary = JSON.parse(results);

            const comment = `## Performance Test Results

            - **Throughput**: ${summary.throughput} req/s
            - **P50 Latency**: ${summary.p50}ms
            - **P95 Latency**: ${summary.p95}ms
            - **P99 Latency**: ${summary.p99}ms
            - **Success Rate**: ${summary.successRate}%

            [Full Report](https://staging.phoenix-distributed.com/performance/${{ github.sha }})`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # Rollback on failure
  rollback:
    name: Rollback Deployment
    needs: [deploy-staging, deploy-production]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
          fi

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} \
            --name phoenix-${{ steps.env.outputs.ENVIRONMENT }}

      - name: Rollback Helm release
        run: |
          helm rollback phoenix-stack -n phoenix-system

      - name: Notify team
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "Deployment rollback executed",
              attachments: [{
                color: 'danger',
                title: 'Rollback Alert',
                text: 'Deployment to ${{ steps.env.outputs.ENVIRONMENT }} failed and was rolled back',
                fields: [{
                  title: 'Environment',
                  value: '${{ steps.env.outputs.ENVIRONMENT }}',
                  short: true
                }, {
                  title: 'Commit',
                  value: '${{ github.sha }}',
                  short: true
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # Release artifacts
  release:
    name: Create Release
    needs: [test, build]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create release notes
        id: notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          cat > release-notes.md << EOF
          # Phoenix SDK $VERSION

          ## What's New
          - Enhanced performance with adaptive QUIC transport
          - Improved certificate management with TrustChain
          - Native monitoring without external dependencies
          - Global CDN for faster SDK distribution

          ## Downloads
          - [Phoenix CLI (Linux)](https://releases.phoenix-distributed.com/$VERSION/phoenix-cli-linux)
          - [Phoenix CLI (macOS)](https://releases.phoenix-distributed.com/$VERSION/phoenix-cli-macos)
          - [Phoenix CLI (Windows)](https://releases.phoenix-distributed.com/$VERSION/phoenix-cli-windows.exe)

          ## Docker Images
          \`\`\`bash
          docker pull phoenix-distributed/phoenix-transport:$VERSION
          docker pull phoenix-distributed/phoenix-certs:$VERSION
          docker pull phoenix-distributed/phoenix-dashboard:$VERSION
          \`\`\`

          ## Installation
          \`\`\`bash
          curl -L https://get.phoenix-distributed.com | bash
          \`\`\`

          ## Documentation
          - [Getting Started](https://docs.phoenix-distributed.com/getting-started)
          - [API Reference](https://docs.phoenix-distributed.com/api)
          - [Migration Guide](https://docs.phoenix-distributed.com/migration)
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Phoenix SDK ${{ steps.notes.outputs.VERSION }}
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-beta') }}
          files: |
            artifacts/**/*.tar.gz
            artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}