// Copyright © 2026 Hypermesh Foundation. All rights reserved.
// Licensed under the Business Source License 1.1.
// See the LICENSE file in the repository root for full license text.

/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface AdvancedMathUtilsInterface extends utils.Interface {
  functions: {
    "BASIS_POINTS()": FunctionFragment;
    "CONVERGENCE_THRESHOLD()": FunctionFragment;
    "E_APPROXIMATION()": FunctionFragment;
    "MAX_ITERATIONS()": FunctionFragment;
    "PRECISION()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BASIS_POINTS"
      | "CONVERGENCE_THRESHOLD"
      | "E_APPROXIMATION"
      | "MAX_ITERATIONS"
      | "PRECISION"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONVERGENCE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "E_APPROXIMATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ITERATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRECISION", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONVERGENCE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "E_APPROXIMATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ITERATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRECISION", data: BytesLike): Result;

  events: {};
}

export interface AdvancedMathUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AdvancedMathUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASIS_POINTS(overrides?: CallOverrides): Promise<[BigNumber]>;

    CONVERGENCE_THRESHOLD(overrides?: CallOverrides): Promise<[BigNumber]>;

    E_APPROXIMATION(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  BASIS_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

  CONVERGENCE_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

  E_APPROXIMATION(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_ITERATIONS(overrides?: CallOverrides): Promise<BigNumber>;

  PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    BASIS_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

    CONVERGENCE_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

    E_APPROXIMATION(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    BASIS_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

    CONVERGENCE_THRESHOLD(overrides?: CallOverrides): Promise<BigNumber>;

    E_APPROXIMATION(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<BigNumber>;

    PRECISION(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    BASIS_POINTS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONVERGENCE_THRESHOLD(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    E_APPROXIMATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
