[package]
name = "hypermesh-security"
version = "0.1.0"
edition = "2021"
authors = ["HyperMesh Team"]
description = "HyperMesh Security Layer"


[lib]
path = "lib.rs"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1"
futures = "0.3"
uuid = { version = "1.0", features = ["v4"] }

# Simplified dependencies for MVP implementation
# Note: In production, would use actual eBPF, HSM, and ML libraries

# Basic cryptography
ring = "0.16"

# System integration
nix = "0.27"
libc = "0.2"

# Monitoring and observability

# Time and scheduling
chrono = { version = "0.4", features = ["serde"] }